language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install nose coverage
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=meshparser
